### ISSUE TITLE
[Bug] Hive 3.1 cannot recognize TIMESTAMP type

### ISSUE THREAD

**Issue by yuzelin** [apache/incubator-paimon#1197]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

Hive 3.1

### Minimal reproduce step

Hive 3.1 reads table with timestamp column.

### What doesn't meet your expectations?

Caused by: java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
  at java.sql/java.sql.Timestamp.valueOf(Unknown Source)
  at org.apache.hive.jdbc.HiveBaseResultSet.evaluate(HiveBaseResultSet.java:443)
  at org.apache.hive.jdbc.HiveBaseResultSet.getColumnValue(HiveBaseResultSet.java:423)
  ... 17 more

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
Duplicate with #1198
