### ISSUE TITLE
[Bug] ProjectCollector is not thread-safe

### ISSUE THREAD

**Issue by nonggialiang** [apache/incubator-paimon#1211]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4-SNAPSHOT

### Compute Engine

flink 1.14.0

### Minimal reproduce step

table-type:  

- write-mode=append-only
- log.system=kafka  

operation:  
- streaming write new data into the table
- stream read with scan.mode=latest-full
- 

### What doesn't meet your expectations?

```
java.lang.NullPointerException
	at org.apache.flink.table.runtime.typeutils.StringDataSerializer.copy(StringDataSerializer.java:56)
	at org.apache.flink.table.runtime.typeutils.StringDataSerializer.copy(StringDataSerializer.java:34)
	at org.apache.flink.table.runtime.typeutils.RowDataSerializer.copyRowData(RowDataSerializer.java:170)
	at org.apache.flink.table.runtime.typeutils.RowDataSerializer.copy(RowDataSerializer.java:131)
	at org.apache.flink.table.runtime.typeutils.RowDataSerializer.copy(RowDataSerializer.java:48)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:80)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29)
	at org.apache.flink.streaming.runtime.tasks.SourceOperatorStreamTask$AsyncDataOutputToOutput.emitRecord(SourceOperatorStreamTask.java:196)
	at org.apache.flink.streaming.api.operators.source.SourceOutputWithWatermarks.collect(SourceOutputWithWatermarks.java:110)
	at org.apache.flink.connector.kafka.source.reader.KafkaRecordEmitter.emitRecord(KafkaRecordEmitter.java:36)
	at org.apache.flink.connector.kafka.source.reader.KafkaRecordEmitter.emitRecord(KafkaRecordEmitter.java:27)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:143)
	at org.apache.flink.connector.base.source.hybrid.HybridSourceReader.pollNext(HybridSourceReader.java:85)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:342)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:496)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:809)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:761)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
	at java.lang.Thread.run(Thread.java:748)
```

### Anything else?

I think the root cause comes from:

- KafkaSourceReader use a seperate thread for SplitFetcher to fetch record from kafka, and decode the record before put it into the queue for SplitReader
- But the KafkaLogDeserializationSchema$ProjectCollector reuse a ProjectedRowData for the record it decoded, so the ProjectedRowData put to queue and waiting for SplitReader to consume may be replaced with new RowData in the fetcher thread.

Fix may be:
Make new ProjectedRowData object for every record the ProjectCollector collects.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by reswqa** [comment]
In order to support `object-reuse`, FLINK-25132 moving deserialization to `RecordEmitter`, which allows for `ProjectedRowData` reuse in the mailbox thread.  

You should use flink 1.14.3 or later to solve this problem.

**Comment by JingsongLi** [comment]
thanks @reswqa ! we don't need to document this, it is a bug, and flink already fixed it.
