### ISSUE TITLE
[Bug]  NPE after using  flink manage memory 

### ISSUE THREAD

**Issue by wg1026688210** [apache/incubator-paimon#1332]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

```
 2023-06-08 12:47:49
java.io.IOException: java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.paimon.flink.sink.RowDataStoreWriteOperator.processElement(RowDataStoreWriteOperator.java:161)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:237)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.processElement(AbstractStreamTaskNetworkInput.java:146)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:110)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:550)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:839)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:788)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:952)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:931)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:745)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.paimon.memory.MemoryPoolFactory.preemptMemory(MemoryPoolFactory.java:63)
	at org.apache.paimon.memory.MemoryPoolFactory.access$200(MemoryPoolFactory.java:27)
	at org.apache.paimon.memory.MemoryPoolFactory$OwnerMemoryPool.nextSegment(MemoryPoolFactory.java:98)
	at org.apache.paimon.data.SimpleCollectingOutputView.nextSegment(SimpleCollectingOutputView.java:69)
	at org.apache.paimon.data.AbstractPagedOutputView.advance(AbstractPagedOutputView.java:122)
	at org.apache.paimon.data.SimpleCollectingOutputView.reset(SimpleCollectingOutputView.java:59)
	at org.apache.paimon.sort.BinaryInMemorySortBuffer.tryInitialize(BinaryInMemorySortBuffer.java:120)
	at org.apache.paimon.sort.BinaryInMemorySortBuffer.write(BinaryInMemorySortBuffer.java:166)
	at org.apache.paimon.mergetree.SortBufferWriteBuffer.put(SortBufferWriteBuffer.java:106)
	at org.apache.paimon.mergetree.MergeTreeWriter.write(MergeTreeWriter.java:146)
	at org.apache.paimon.mergetree.MergeTreeWriter.write(MergeTreeWriter.java:53)
	at org.apache.paimon.operation.AbstractFileStoreWrite.write(AbstractFileStoreWrite.java:100)
	at org.apache.paimon.table.sink.TableWriteImpl.writeAndReturn(TableWriteImpl.java:101)
	at org.apache.paimon.flink.sink.StoreSinkWriteImpl.write(StoreSinkWriteImpl.java:91)
	at org.apache.paimon.flink.sink.GlobalFullCompactionSinkWrite.write(GlobalFullCompactionSinkWrite.java:100)
	at org.apache.paimon.flink.sink.RowDataStoreWriteOperator.processElement(RowDataStoreWriteOperator.java:159)
	... 13 more
Caused by: java.lang.NullPointerException
	at java.lang.System.arraycopy(Native Method)
	at org.apache.hadoop.io.Text.set(Text.java:225)
	at org.apache.paimon.shade.org.apache.orc.impl.StringRedBlackTree.add(StringRedBlackTree.java:59)
	at org.apache.paimon.shade.org.apache.orc.impl.writer.StringTreeWriter.writeBatch(StringTreeWriter.java:70)
	at org.apache.paimon.shade.org.apache.orc.impl.writer.StructTreeWriter.writeRootBatch(StructTreeWriter.java:56)
	at org.apache.paimon.shade.org.apache.orc.impl.WriterImpl.addRowBatch(WriterImpl.java:557)
	at org.apache.paimon.format.orc.writer.OrcBulkWriter.flush(OrcBulkWriter.java:60)
	at org.apache.paimon.io.SingleFileWriter.close(SingleFileWriter.java:143)
	at org.apache.paimon.io.RollingFileWriter.closeCurrentWriter(RollingFileWriter.java:111)
	at org.apache.paimon.io.RollingFileWriter.close(RollingFileWriter.java:151)
	at org.apache.paimon.mergetree.MergeTreeWriter.flushWriteBuffer(MergeTreeWriter.java:208)
	at org.apache.paimon.mergetree.MergeTreeWriter.flushMemory(MergeTreeWriter.java:180)
	at org.apache.paimon.memory.MemoryPoolFactory.preemptMemory(MemoryPoolFactory.java:61)
```

### Compute Engine

flink v1.17.0

### Minimal reproduce step

1.  set manage memory 3.5GB
2.  use flink manage memory   /*+ OPTIONS('sink.use-managed-memory-allocator'='true', 'sink.managed.writer-buffer-memory'='256M') */

### What doesn't meet your expectations?

Is the memory management insufficient And Paimon did not give a clear reminder.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by q977734161** [comment]
I'm willing to fix this bug

**Comment by FangYongs** [comment]
Thanks @q977734161 , assigned

**Comment by JingsongLi** [comment]
How is the progress? @q977734161

**Comment by q977734161** [comment]
I built a cluster and used Flink manage memory for data insertion testing. After many attempts, I did not find this exception. Can you provide more specific data。

**Comment by wg1026688210** [comment]
The size of single row is very large ,  greater than  1MB

**Comment by wg1026688210** [comment]
> I built a cluster and used Flink manage memory for data insertion testing. After many attempts, I did not find this exception. Can you provide more specific data。

CREATE CATALOG my_catalog WITH (
    'type' = 'paimon',
    'warehouse'='viewfs://xxxx/team/db/hive_db/aa'
)
########################################################
USE CATALOG my_catalog
########################################################
CREATE DATABASE IF NOT EXISTS rt_feature_db
########################################################
USE rt_feature_db
########################################################
CREATE TEMPORARY TABLE feature_click_sight
              (
              pvID String,
              deviceID String,
              objectType String ,
              rType String ,
              objectID String ,
              sightObjectP String ,
              isClick String ,
              itermFeature String ,
              userFeature String ,
              startTime String ,
              pushTime String ,
              rcmReqFeature String ,
              labelTag String ,
              actTimestamp bigint ,
              pushTimestamp bigint,
              serverTime bigint,
              `kafka_meta_ts` TIMESTAMP(3) METADATA FROM 'timestamp',
              time_ltz AS TO_TIMESTAMP_LTZ(serverTime, 3),
              WATERMARK FOR time_ltz AS time_ltz - INTERVAL '5' MINUTE
              ) WITH (
               'connector' = 'kafka',
               'topic' = 'feature_dump_join_phase2',
               'properties.bootstrap.servers' = 'xxxx:9092',
               'properties.group.id' = 'join_phase3_v11_2',
               'properties.auto.offset.reset'='latest',
               'properties.client.id' = 'dc',
               'properties.register.consumer.metrics'='true',
               'format' = 'json',
               'json.fail-on-missing-field' = 'false',
               'json.ignore-parse-errors' = 'true'
               )
########################################################
CREATE TEMPORARY TABLE feature_interaction
(
              pvid String ,
              device_id String,
              biz_type String,
              biz_id  String ,
              classid String,
              user_id String ,
              source_id String,
              interact_type String,
              create_time bigint,
              `kafka_meta_ts` TIMESTAMP(3) METADATA FROM 'timestamp',
              time_ltz AS TO_TIMESTAMP_LTZ(create_time, 3),
              WATERMARK FOR time_ltz AS time_ltz - INTERVAL '5' MINUTE
) WITH (
               'connector' = 'kafka',
               'topic' = 'feature_dump_join_phase3',
               'properties.bootstrap.servers' = 'xxxx:9092',
               'properties.group.id' = 'join_phase3_v11_1',
               'properties.auto.offset.reset'='latest',
               'properties.client.id' = 'dc',
               'properties.register.consumer.metrics'='true',
               'format' = 'json',
               'json.fail-on-missing-field' = 'false',
               'json.ignore-parse-errors' = 'true'
               )
########################################################
CREATE TEMPORARY SYSTEM FUNCTION
  IF NOT EXISTS addInteractionAroundCurrentHour
  AS 'com.autohome.data.InteractionAroundHourAdder' LANGUAGE JAVA
########################################################
CREATE TABLE if not exists join_phase3_v11 (
                pvid String,
                device_id String,
                object_type String ,
                rtype String,
                object_id String ,
                sight_object_p String ,
                is_click String ,
                iterm_feature String ,
                user_feature String ,
                start_time String ,
                push_time String ,
                rcm_req_feature String ,
                label_tag String ,
                is_praise String,
                is_favorites String,
                is_comment String ,
                is_share String ,
                is_attention String ,
                is_dis_attention String ,
                kafka_meta_time_left String,
                kafka_meta_time_right String,
                dt String ,
                `hour` String ,
                primary key (pvid,device_id,object_type,object_id,dt,`hour`) not enforced
                ) partitioned by (dt,`hour`)
                WITH (
                'bucket' = '128',
                'bucket-key' ='pvid',
                'merge-engine' ='partial-update',
                'partition.expiration-time' = '7 d',
                'partition.expiration-check-interval' = '1 d',
                'partition.timestamp-formatter' = 'yyyy-MM-dd',
                'snapshot.num-retained.max' ='2',
                'snapshot.num-retained.min' ='1',
                'snapshot.time-retained' ='30m',
                'read.batch-size'='100',
                'full-compaction.delta-commits'='5',
                'page-size' ='256 kb',
                'target-file-size'='256 mb',
                'sort-engine'='min-heap'
                )
########################################################

insert into join_phase3_v11
select pvID,
       UPPER(deviceID),
       objectType,
       rType,
       objectID,
       sightObjectP,
       isClick,
       itermFeature,
       userFeature,
       startTime,
       pushTime,
       rcmReqFeature,
       labelTag,
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       DATE_FORMAT(kafka_meta_ts, 'yyyy-MM-dd HH'),
              JSON_STRING(CAST(NULL AS INT)),

       DATE_FORMAT(time_ltz, 'yyyy-MM-dd'),
       DATE_FORMAT(time_ltz, 'HH')
from feature_click_sight
union all
select pvid1,
       UPPER(device_id1),
       biz_type1,
       JSON_STRING(CAST(NULL AS INT)),
       biz_id1,
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       JSON_STRING(CAST(NULL AS INT)),
       CASE WHEN interact_type1='praise' THEN '1' ELSE JSON_STRING(CAST(NULL AS INT))  END  ,
       CASE WHEN interact_type1='favorites' THEN '1' ELSE JSON_STRING(CAST(NULL AS INT))  END  ,
       CASE WHEN interact_type1='comment' THEN '1' ELSE JSON_STRING(CAST(NULL AS INT))  END  ,
       CASE WHEN interact_type1='share' THEN '1' ELSE JSON_STRING(CAST(NULL AS INT))  END  ,
       CASE WHEN interact_type1='attention' and classid1 ='0' THEN '1' ELSE JSON_STRING(CAST(NULL AS INT))  END  ,
       CASE WHEN interact_type1='attention' and classid1 ='1' THEN '1' ELSE JSON_STRING(CAST(NULL AS INT))  END  ,
              JSON_STRING(CAST(NULL AS INT)),
       DATE_FORMAT(kafka_meta_ts, 'yyyy-MM-dd HH'),
       DATE_FORMAT(time_ltz1, 'yyyy-MM-dd'),
       DATE_FORMAT(time_ltz1, 'HH')
from feature_interaction JOIN LATERAL TABLE(addInteractionAroundCurrentHour(pvid,device_id,biz_type,biz_id,interact_type,classid,time_ltz)) ON TRUE
where
interact_type1 <>'' and interact_type1 is not null
and pvid1 <>'' and pvid1 is not null
and device_id1 <>'' and device_id1 is not null
and biz_type1 <> '' and biz_type1 is not null
and biz_id1 <> '' and biz_id1 is not null
and source_id <> '' and source_id is not null

**Comment by wg1026688210** [comment]
maybe we can try lowering this parameter  'sink.managed.writer-buffer-memory'='256M'

**Comment by q977734161** [comment]
I'll give it a try and see the results

**Comment by q977734161** [comment]
I tried many times and still didn't get this exception, and then I tried to write code to trigger this exception, my code is as follows
Mainly when inserting the third record, the second column of data does not give any value.
`		Options tableOptions = new Options();
        tableOptions.setString("orc.codec", "snappy");
        FileFormat fileFormat = FileFormat.fromIdentifier("orc", tableOptions);
        //FileFormat fileFormat = createFileFormat(format, codec);
        RowType rowType =
                RowType.builder().fields(Arrays.asList(new IntType(), new VarCharType())).build();

        Path path = new Path(tempDir.toUri().toString(), "1." + format);

        // write
        List<InternalRow> insertRow = new ArrayList<>();
        insertRow.add(GenericRow.of(1, BinaryString.fromString("1")));
        insertRow.add(GenericRow.of(2, BinaryString.fromString("2")));
        insertRow.add(GenericRow.of(3));
        PositionOutputStream out = new LocalFileIO().newOutputStream(path, false);
        FormatWriter writer = fileFormat.createWriterFactory(rowType).create(out, "LZ4");
        for (InternalRow row : insertRow) {
            writer.addElement(row);
        }
        writer.flush();
        out.close();`
  This exception will occur after execution.
` java.lang.NullPointerException
	at java.lang.System.arraycopy(Native Method)
	at org.apache.hadoop.io.Text.set(Text.java:225)
	at org.apache.orc.impl.StringRedBlackTree.add(StringRedBlackTree.java:59)
	at org.apache.orc.impl.writer.VarcharTreeWriter.writeTruncated(VarcharTreeWriter.java:68)
	at org.apache.orc.impl.writer.VarcharTreeWriter.writeBatch(VarcharTreeWriter.java:57)
	at org.apache.orc.impl.writer.StructTreeWriter.writeRootBatch(StructTreeWriter.java:56)
	at org.apache.orc.impl.WriterImpl.addRowBatch(WriterImpl.java:557)
	at org.apache.paimon.format.orc.writer.OrcBulkWriter.flush(OrcBulkWriter.java:73)
	at org.apache.paimon.format.BulkFileFormatTest.testFormatWriteRead(BulkFileFormatTest.java:83)
	at org.apache.paimon.format.BulkFileFormatTest.testOrc(BulkFileFormatTest.java:51)`

So I suspect that this is not a problem with Paimon, but rather that some data is missing when converting sql to InternalRow.

**Comment by wg1026688210** [comment]
Hi~ @q977734161  nice done for reproducing by code .

**Comment by FangYongs** [comment]
@q977734161 Good job! It looks like illegal data for orc?  @JingsongLi Can you see anything wrong with this stack?

**Comment by q977734161** [comment]
@wg1026688210 It should not be caused by concurrency issues, the specific reasons need to be discussed.

**Comment by wg1026688210** [comment]
@q977734161 @FangYongs 
Explain my thoughts :from the exception stack trace I posted, it seems that the issue occurred when different writers preempt the writer buffer. When the buffer is not sufficient, the writer with the largest memory usage will be closed. Is it possible that this could close a writer which  is currently writing data at another thread? I wrote some simple unit tests before, but I wasn't able to reproduce the issue. I apologize that I haven't had enough time to follow up on this lately due to some other matters. If there are any new developments on this issue in the future, I would be happy to continue participating in the discussion.
