### ISSUE TITLE
[Bug] MergeTreeTestWithMinHeap.testPrepareCommitRecycleReference is not stable

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#1653]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

https://github.com/apache/incubator-paimon/actions/runs/5655364193/job/15320333630?pr=1603

Error:  Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.319 s <<< FAILURE! - in org.apache.paimon.mergetree.MergeTreeTestBase$MergeTreeTestWithMinHeap
Error:  org.apache.paimon.mergetree.MergeTreeTestBase$MergeTreeTestWithMinHeap.testPrepareCommitRecycleReference  Time elapsed: 0.196 s  <<< ERROR!
java.io.IOException: Failed to delete temp directory /tmp/junit1593590598298920766. The following paths could not be deleted (see suppressed exceptions for details): , bucket-0
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:280)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:188)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$closeAllStoredCloseableValues$3(ExtensionValuesStore.java:68)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)

### Compute Engine

all

### Minimal reproduce step

ci failed

### What doesn't meet your expectations?

ci failed

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liming30** [comment]
I would like to create a PR to fix this later.
