### ISSUE TITLE
[Question] how to check BinaryRow's value

### ISSUE THREAD

**Issue by liunaijie** [apache/incubator-paimon#1709]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4-SNAPSHOT

### Compute Engine

SeaTunnel

### Minimal reproduce step

Now I use SeaTunnel write data to Paimon. 
But get NPE when write data. From the SeaTunnel log i can see the record schema and value all is not null. 

SeaTunnel write
```
        if (Objects.isNull(tableWrite)) {
            tableWrite = table.newBatchWriteBuilder().newWrite();
        }
        InternalRow rowData = RowConverter.convert(element, seaTunnelRowType);
        try {
            tableWrite.write(rowData);
        } catch (Exception e) {
            throw new PaimonConnectorException(
                    PaimonConnectorErrorCode.TABLE_WRITE_RECORD_FAILED,
                    "This record " + element + " failed to be written",
                    e);
        }
```

Error message:
```
 Caused by: java.lang.NullPointerException
 	at org.apache.paimon.format.orc.writer.RowDataVectorizer.setColumn(RowDataVectorizer.java:104)
 	at org.apache.paimon.format.orc.writer.RowDataVectorizer.vectorize(RowDataVectorizer.java:61)
 	at org.apache.paimon.format.orc.writer.RowDataVectorizer.vectorize(RowDataVectorizer.java:48)
 	at org.apache.paimon.format.orc.writer.OrcBulkWriter.addElement(OrcBulkWriter.java:63)
 	at org.apache.paimon.io.SingleFileWriter.writeImpl(SingleFileWriter.java:102)
 	at org.apache.paimon.io.StatsCollectingSingleFileWriter.write(StatsCollectingSingleFileWriter.java:65)
 	at org.apache.paimon.io.RowDataFileWriter.write(RowDataFileWriter.java:71)
 	at org.apache.paimon.io.RowDataFileWriter.write(RowDataFileWriter.java:41)
 	at org.apache.paimon.io.RollingFileWriter.write(RollingFileWriter.java:82)
 	at org.apache.paimon.append.AppendOnlyWriter.write(AppendOnlyWriter.java:109)
 	at org.apache.paimon.append.AppendOnlyWriter.write(AppendOnlyWriter.java:50)
 	at org.apache.paimon.operation.AbstractFileStoreWrite.write(AbstractFileStoreWrite.java:93)
 	at org.apache.paimon.table.sink.TableWriteImpl.writeAndReturn(TableWriteImpl.java:94)
 	at org.apache.paimon.table.sink.TableWriteImpl.write(TableWriteImpl.java:83)
```

### What doesn't meet your expectations?

is there any way to check or print the BinaryRow's value to help debug issue

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
Hi, if you know the schema of the data, you can convert `InternalRow` to readable Java object  by `InternalRow.FieldGetter`. You can see the test class `DataFormatTestUtil`, maybe its method can help you.

**Comment by liunaijie** [comment]
it's helpful, thanks
