### ISSUE TITLE
[Bug] MySqlSyncDatabaseTableListITCase.testActionRunResult is not stable

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#1781]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 81.715 s <<< FAILURE! - in org.apache.paimon.flink.action.cdc.mysql.MySqlSyncDatabaseTableListITCase
Error:  org.apache.paimon.flink.action.cdc.mysql.MySqlSyncDatabaseTableListITCase.testActionRunResult  Time elapsed: 61.176 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting actual:
  ["shard_2_t3",
    "shard_2_t1",
    "shard_1_t2",
    "shard_2_t22",
    "shard_1_t3",
    "shard_2_tb",
    "shard_1_t11",
    "x_shard_1_t1",
    "shard_1_s2",
    "shard_1_taa"]
to contain exactly in any order:
  ["shard_1_t11",
    "shard_1_t2",
    "shard_1_t3",
    "shard_1_taa",
    "shard_1_s2",
    "shard_2_t1",
    "shard_2_t22",
    "shard_2_t3",
    "shard_2_tb",
    "x_shard_1_t1",
    "shard_2_s3",
    "shard_3_tab"]
but could not find the following elements:
  ["shard_2_s3", "shard_3_tab"]

	at org.apache.paimon.flink.action.cdc.mysql.MySqlSyncDatabaseTableListITCase.testActionRunResult(MySqlSyncDatabaseTableListITCase.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)

https://github.com/apache/incubator-paimon/actions/runs/5805455859/job/15736585551?pr=1693

### Compute Engine

flink

### Minimal reproduce step

ci

### What doesn't meet your expectations?

ci

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liming30** [comment]
@FangYongs It seems to be the same issue as #1750 , I added 10 retries in the latest pr, but it still doesn't seem to be fully fixed. @yuzelin @zhuangchong Do you have any other suggestions?

**Comment by yuzelin** [comment]
I think I can fix it. The CDC job has two phase: snapshot and incremental. The failed test is trying to check the result of incremental phase. I can add some code to ensure the job go into that phase. @liming30

**Comment by FangYongs** [comment]
@yuzelin 👍 This failure occurs quite frequently, and it would be great if it could be fixed.

**Comment by yuzelin** [comment]
I think #1783 fixes it. Let's see whether the error will occur again.

**Comment by yuzelin** [comment]
Seems this error is fixed.
