### ISSUE TITLE
[Bug] paimon-spark3.1 reports error when writing data

### ISSUE THREAD

**Issue by xwmr-max** [apache/incubator-paimon#1968]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6

### Compute Engine

spark3.1

### Minimal reproduce step

Add the paimon-spark-runtime jar to the spark3.1 compute engine, create a new paimon table, and an error will be reported when writing data.

### What doesn't meet your expectations?

an error will be reported when writing data.

### Anything else?

The error log is as follows：
```java

java.lang.NoClassDefFoundError: org/apache/spark/sql/connector/write/Write
	at org.apache.paimon.spark.SparkTable.newWriteBuilder(SparkTable.java:99)
	at org.apache.spark.sql.execution.datasources.v2.V1FallbackWriters.newWriteBuilder(V1FallbackWriters.scala:107)
	at org.apache.spark.sql.execution.datasources.v2.V1FallbackWriters.newWriteBuilder$(V1FallbackWriters.scala:102)
	at org.apache.spark.sql.execution.datasources.v2.AppendDataExecV1.newWriteBuilder(V1FallbackWriters.scala:38)
	at org.apache.spark.sql.execution.datasources.v2.AppendDataExecV1.run(V1FallbackWriters.scala:45)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:40)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:40)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:46)
	at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:232)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3699)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:108)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:170)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:91)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:780)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3697)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:232)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:780)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:780)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:650)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:67)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:400)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1(SparkSQLCLIDriver.scala:521)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1$adapted(SparkSQLCLIDriver.scala:515)

```
Judging from the code, there is no code adapted to spark3.1. What are the considerations for this?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xwmr-max** [comment]
cc @yuzelin

**Comment by yuzelin** [comment]
Hi, thanks for reporting. I have asked the community members and they told me that writing is not supported for Spark 3.1 now.
