### ISSUE TITLE
[Bug] Database default does not exist in Catalog

### ISSUE THREAD

**Issue by ngk2009** [apache/incubator-paimon#2310]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6

### Compute Engine

Flink

### Minimal reproduce step

CREATE CATALOG my_catalog WITH (
    'type' = 'paimon',
    'warehouse' = 's3://lakehouse/paimon',
    's3.endpoint' = 'http://25.30.9.250:9200',
    's3.access-key' = 'root',
    's3.secret-key' = '12345678'
);
use catalog my_catalog;
CREATE TABLE word_count (
    word STRING PRIMARY KEY NOT ENFORCED,
    cnt BIGINT
);

### What doesn't meet your expectations?

[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.catalog.exceptions.DatabaseNotExistException: Database default does not exist in Catalog my_catalog.

### Anything else?

sql-client log:
Caused by: org.apache.flink.table.catalog.exceptions.DatabaseNotExistException: Database default does not exist in Catalog my_catalog.
	at org.apache.paimon.flink.FlinkCatalog.createTable(FlinkCatalog.java:312)
	at org.apache.flink.table.catalog.CatalogManager.lambda$createTable$18(CatalogManager.java:957)
	at org.apache.flink.table.catalog.CatalogManager.execute(CatalogManager.java:1290)
	... 16 more

End of exception on server side>]
	at org.apache.flink.runtime.rest.RestClient.parseResponse(RestClient.java:646) ~[flink-dist-1.18.0.jar:1.18.0]
	at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$6(RestClient.java:626) ~[flink-dist-1.18.0.jar:1.18.0]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ngk2009** [comment]
This problem occurs when flinks-s3-fs-presto is used, but Flinks-s3-fs-Hadoop is normal

**Comment by ngk2009** [comment]
S3FileIO uses S3AFileSystem of Hadoop, so it cannot be used successfully. Could you consider specifically stating that s3p cannot be used in the usage instructions

**Comment by luyizhizaio** [comment]
paimon 0.8,I had the same problem
