### ISSUE TITLE
[Bug] java.lang.UnsupportedOperationException with Trino 435

### ISSUE THREAD

**Issue by macdoor** [apache/incubator-paimon#2514]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

paimon-trino-422-0.7-20231215.000522-5.jar
paimon-s3-0.7-20231215.002053-27.jar

### Compute Engine

Trino 435

### Minimal reproduce step

```
create table word_count
(
    word string,
    cnt bigint
);

select * from word_count;
```

It works properly under trino 422

### What doesn't meet your expectations?

give query result

### Anything else?

```
2023-12-15T12:44:14.028+0800    INFO    main    io.trino.server.Server  ======== SERVER STARTED ========
2023-12-15T12:44:20.278+0800    DEBUG   dispatcher-query-0      io.trino.security.AccessControl Invocation of checkCanSetUser(principal=Optional[admin], userName='admin') succeeded in 334.65us
2023-12-15T12:44:20.281+0800    DEBUG   dispatcher-query-0      io.trino.security.AccessControl Invocation of checkCanExecuteQuery(identity=Identity{user='admin', principal=admin}) succeeded in 172.35us
2023-12-15T12:44:20.314+0800    DEBUG   dispatcher-query-1      io.trino.execution.QueryStateMachine    Query 20231215_044420_00000_6crj2 is QUEUED
2023-12-15T12:44:20.322+0800    DEBUG   dispatcher-query-4      io.trino.execution.QueryStateMachine    Query 20231215_044420_00000_6crj2 is WAITING_FOR_RESOURCES
2023-12-15T12:44:20.348+0800    DEBUG   dispatcher-query-1      io.trino.execution.QueryStateMachine    Query 20231215_044420_00000_6crj2 is FAILED
2023-12-15T12:44:20.348+0800    DEBUG   dispatcher-query-2      io.trino.execution.QueryStateMachine    Query 20231215_044420_00000_6crj2 failed
java.lang.UnsupportedOperationException
        at io.trino.spi.connector.Connector.beginTransaction(Connector.java:50)
        at io.trino.metadata.Catalog.beginTransaction(Catalog.java:134)
        at io.trino.metadata.Catalog.beginTransaction(Catalog.java:108)
        at io.trino.transaction.InMemoryTransactionManager$TransactionMetadata.getTransactionCatalogMetadata(InMemoryTransactionManager.java:462)
        at java.base/java.util.Optional.map(Optional.java:260)
        at io.trino.transaction.InMemoryTransactionManager.getOptionalCatalogMetadata(InMemoryTransactionManager.java:212)
        at io.trino.metadata.MetadataManager.getOptionalCatalogMetadata(MetadataManager.java:2569)
        at io.trino.metadata.MetadataManager.getMaterializedViewInternal(MetadataManager.java:1692)
        at io.trino.metadata.MetadataManager.getMaterializedView(MetadataManager.java:1654)
        at io.trino.tracing.TracingMetadata.getMaterializedView(TracingMetadata.java:1360)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2253)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:521)
        at io.trino.sql.tree.Table.accept(Table.java:60)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:540)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:2858)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:521)
        at io.trino.sql.tree.AliasedRelation.accept(AliasedRelation.java:71)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:540)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4869)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3062)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:521)
        at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:540)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:548)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1558)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:521)
        at io.trino.sql.tree.Query.accept(Query.java:118)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:540)
        at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:500)
        at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:489)
        at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:97)
        at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
        at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:274)
        at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
        at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:850)
        at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
        at io.trino.$gen.Trino_435____20231215_044357_2.call(Unknown Source)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)

```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by shidayang** [comment]
This is due to the removal of the Connector.beginTransaction(IsolationLevel isolationLevel, boolean readOnly) method in the higher version of Trino.
