### ISSUE TITLE
[Bug] paimon-0.6 flink-1.18.0 savepoint  start 404 data file

### ISSUE THREAD

**Issue by zck573693104** [apache/incubator-paimon#2590]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

paimon-0.6
flink-1.18.0

### Compute Engine

flink-1.18.0

### Minimal reproduce step

1. run savepoint
2. from savepoint start

### What doesn't meet your expectations?

source(kafka) into paimon table,table with par
     'bucket' = '-1',
	'snapshot.num-retained.min'= '1',
	'snapshot.num-retained.max'= '10',
	'file.format' = 'parquet',
    'file.compression'='zstd',
    'write-buffer-spillable'='true',
    'target-file-size'='164 mb',
    'snapshot.time-retained'='30 min'

1. run savepoint
2. from savepoint start
3. taskmanager error,
4. Cannot recover from this checkpoint because some files in the snapshot that need to be resubmitted have been deleted

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gfunc** [comment]
I had a similar problem with Paimon 0.7-snapshot and Flink 1.18.0. Can not restore from savepoint/checkpoint either, attached the error below. Switched back to Flink 1.17 solved the problem. 
At first I thought it was a dependency conflict of `snappy` package, but the error persisted after I swapped Hadoop Uber jar with a self-built, `snappy` shaded uber jar. 

I cannot determine if it is a problem with Flink itself or not.

```log
java.lang.Exception: Exception while creating StreamOperatorStateContext.
	at org.apache.flink.streaming.api.operators.StreamTaskStateInitializerImpl.streamOperatorStateContext(StreamTaskStateInitializerImpl.java:258)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:256)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:106)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:753)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:728)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:693)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:953)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:922)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:746)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.NullPointerException
Caused by: org.apache.flink.util.FlinkException: Could not restore operator state backend for CdcRecordStoreMultiWriteOperator_0ad3a6965563b653e7e5b13ffb9bfc60_(4/16) from any of the 1 provided restore options.
	at org.apache.flink.streaming.api.operators.BackendRestorerProcedure.createAndRestore(BackendRestorerProcedure.java:160)
	at org.apache.flink.streaming.api.operators.StreamTaskStateInitializerImpl.operatorStateBackend(StreamTaskStateInitializerImpl.java:289)
	at org.apache.flink.streaming.api.operators.StreamTaskStateInitializerImpl.streamOperatorStateContext(StreamTaskStateInitializerImpl.java:176)
	... 11 more
Caused by: org.apache.flink.runtime.state.BackendBuildingException: Failed when trying to restore operator state backend
	at org.apache.flink.runtime.state.DefaultOperatorStateBackendBuilder.build(DefaultOperatorStateBackendBuilder.java:88)
	at org.apache.flink.contrib.streaming.state.EmbeddedRocksDBStateBackend.createOperatorStateBackend(EmbeddedRocksDBStateBackend.java:533)
	at org.apache.flink.streaming.api.operators.StreamTaskStateInitializerImpl.lambda$operatorStateBackend$0(StreamTaskStateInitializerImpl.java:280)
	at org.apache.flink.streaming.api.operators.BackendRestorerProcedure.attemptCreateAndRestore(BackendRestorerProcedure.java:168)
	at org.apache.flink.streaming.api.operators.BackendRestorerProcedure.createAndRestore(BackendRestorerProcedure.java:135)
	... 13 more
Caused by: java.io.IOException: invalid stream header
	at org.xerial.snappy.SnappyFramedInputStream.<init>(SnappyFramedInputStream.java:149)
	at org.xerial.snappy.SnappyFramedInputStream.<init>(SnappyFramedInputStream.java:102)
	at org.apache.flink.runtime.state.SnappyStreamCompressionDecorator.decorateWithCompression(SnappyStreamCompressionDecorator.java:53)
	at org.apache.flink.runtime.state.StreamCompressionDecorator.decorateWithCompression(StreamCompressionDecorator.java:60)
	at org.apache.flink.runtime.state.CompressibleFSDataInputStream.<init>(CompressibleFSDataInputStream.java:39)
	at org.apache.flink.runtime.state.OperatorStateRestoreOperation.restore(OperatorStateRestoreOperation.java:185)
	at org.apache.flink.runtime.state.DefaultOperatorStateBackendBuilder.build(DefaultOperatorStateBackendBuilder.java:85)
	... 17 more
```

**Comment by yuzelin** [comment]
@gfunc Your problem is not the same. Your problem seems a compatibility problem of of different flink version. His problem is some data files are not found unexpectedly when recovering.

**Comment by zck573693104** [comment]
not bug,because table deleted,sorry.
