### ISSUE TITLE
[Bug] modify paimon table failed when using hive-metastore

### ISSUE THREAD

**Issue by gary0416** [apache/incubator-paimon#2729]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5.0-incubating

### Compute Engine

flink 1.17.1

### Minimal reproduce step

```
CREATE CATALOG paimon_user WITH (
    'type' = 'paimon',
    'warehouse' = 's3://test-paimon/',
    's3.endpoint' = 'http://x.x.x.x:xxx/',
    's3.access-key' = '***',
    's3.secret-key' = '***',
    'fs.s3a.connection.maximum' = '10000',
    'metastore' = 'hive',
    'uri' = 'thrift://x.x.x.x:9083',
    'lock.enabled' = 'true',
    'location-in-properties' = 'true'
);
USE CATALOG paimon_user;
use cdc_multi_tables;

CREATE TABLE test_modify_col_type (
    data_id string,
    data_name1 varchar(10),
    proc_time AS PROCTIME(),
    PRIMARY KEY (data_id) NOT ENFORCED
) WITH (
    'bucket' = '1',
    'sink.managed.writer-buffer-memory'='256 MB',
    'write-manifest-cache'='32mb',
    'num-sorted-run.compaction-trigger'='10',
    'write-buffer-spillable'='true',
    'changelog-producer' = 'input',
    'write-mode' = 'change-log',
    'num-sorted-run.stop-trigger' = '2147483647',
    'sort-spill-threshold' = '10'
);
alter table test_modify_col_type add (new_col1 string);
```

### What doesn't meet your expectations?

got MetaException(message:java.lang.IllegalArgumentException: Can not create a Path from a null string)
```
Caused by: org.apache.flink.table.api.TableException: Could not execute ALTER TABLE paimon_user.cdc_multi_tables.test_modify_col_type
  ADD `new_col1` STRING
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1091)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:765)
	at com.neusoft.oscoe.cndp.FlinkRemoteTest.modifyTable(FlinkRemoteTest.java:264)
	at com.neusoft.oscoe.cndp.FlinkRemoteTest.main(FlinkRemoteTest.java:60)
	... 5 more
Caused by: org.apache.flink.table.api.TableException: Could not execute AlterTable in path `paimon_user`.`cdc_multi_tables`.`test_modify_col_type`
	at org.apache.flink.table.catalog.CatalogManager.execute(CatalogManager.java:915)
	at org.apache.flink.table.catalog.CatalogManager.alterTable(CatalogManager.java:823)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1081)
	... 8 more
Caused by: java.lang.RuntimeException: MetaException(message:java.lang.IllegalArgumentException: Can not create a Path from a null string)
	at org.apache.paimon.hive.HiveCatalog.alterTable(HiveCatalog.java:418)
	at org.apache.paimon.flink.FlinkCatalog.alterTable(FlinkCatalog.java:464)
	at org.apache.flink.table.catalog.CatalogManager.lambda$alterTable$18(CatalogManager.java:826)
	at org.apache.flink.table.catalog.CatalogManager.execute(CatalogManager.java:909)
	... 10 more
Caused by: MetaException(message:java.lang.IllegalArgumentException: Can not create a Path from a null string)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$alter_table_with_environment_context_result$alter_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$alter_table_with_environment_context_result$alter_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$alter_table_with_environment_context_result.read(ThriftHiveMetastore.java)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_alter_table_with_environment_context(ThriftHiveMetastore.java:2270)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.alter_table_with_environment_context(ThriftHiveMetastore.java:2254)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.alter_table_with_environmentContext(HiveMetaStoreClient.java:405)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.alter_table(HiveMetaStoreClient.java:385)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:212)
	at com.sun.proxy.$Proxy18.alter_table(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2773)
	at com.sun.proxy.$Proxy19.alter_table(Unknown Source)
	at org.apache.paimon.hive.HiveCatalog.alterTable(HiveCatalog.java:415)
	... 13 more
```

### Anything else?

hive-metastore is needed because of HiveCatalogLock

hive metastore org.apache.hadoop.hive.metastore.Warehouse#getFileStatusesForUnpartitionedTable：
table.getSd().getLocation() is null，unless using table.getParameters().get("paimon_location")，or method return Collections.emptyList()

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by hongyonggan** [comment]
可以尝试下 location-in-properties=false 进行规避上述问题，如果还有问题，可以参照[[Hive] Using hive table location when catalog is HiveCatalog (#2315)](https://github.com/apache/incubator-paimon/pull/2315)

**Comment by gary0416** [comment]
> > You can try using location-in-properties=false to mitigate the above issue. If there are still problems, you can refer to [[Hive] Using hive table location when catalog is HiveCatalog (#2315)](https://github.com/apache/incubator-paimon/pull/2315).
> 
> When location-in-properties=true, executing alter table does indeed trigger a bug.

Thanks for the reply, according to the docs:
```
If you are using an object storage , and you don't want that the location of paimon table/database is accessed by the filesystem of hive,
which may lead to the error such as "No FileSystem for scheme: s3a".
You can set location in the properties of table/database by the config of `location-in-properties`. See
[setting the location of table/database in properties ]({{< ref "maintenance/configurations#HiveCatalogOptions" >}})
```

I'm using s3 by minio. It seems that location-in-properties=true is a better configuration? Paimon only use HiveCatalogLock by lock.enabled=true, config hive-metastore on s3 is not necessary.

pr 2315 doesn't work, I've tried paimon 0.6.0-incubating and 0.7-SNAPSHOT(2023-12-29).

How to fix or avoid this bug without modify hive-metastore source code?

**Comment by hongyonggan** [comment]
> > > You can try using location-in-properties=false to mitigate the above issue. If there are still problems, you can refer to [[Hive] Using hive table location when catalog is HiveCatalog (#2315)](https://github.com/apache/incubator-paimon/pull/2315).
> > 
> > 
> > When location-in-properties=true, executing alter table does indeed trigger a bug.
> 
> Thanks for the reply, according to the docs:
> 
> ```
> If you are using an object storage , and you don't want that the location of paimon table/database is accessed by the filesystem of hive,
> which may lead to the error such as "No FileSystem for scheme: s3a".
> You can set location in the properties of table/database by the config of `location-in-properties`. See
> [setting the location of table/database in properties ]({{< ref "maintenance/configurations#HiveCatalogOptions" >}})
> ```
> 
> I'm using s3 by minio. It seems that location-in-properties=true is a better configuration? Paimon only use HiveCatalogLock by lock.enabled=true, config hive-metastore on s3 is not necessary.
> 
> pr 2315 doesn't work, I've tried paimon 0.6.0-incubating and 0.7-SNAPSHOT(2023-12-29).
> 
> How to fix or avoid this bug without modify hive-metastore source code?

This actually involves two issues:
  1. HMS itself integrates too many path validations specific to the Hive engine, and it is not just about managing metadata information. After creating a table, even with `location-in-properties=true`, it will automatically add a path under the default configuration of the HMS service's warehouse. This process must go through the filesystem, and improper usage can lead to other issues.
  2. To address this problem when integrating Paimon with HMS, try adding the parameter `DO_NOT_UPDATE_STATS=false` in the table properties. This should help resolve the issue.

The above is my response, hoping it solves your problem. Thank you.
