### ISSUE TITLE
[Bug] insert into Paimon Tables  failed when using hive-metastore

### ISSUE THREAD

**Issue by www2388258980** [apache/incubator-paimon#2804]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6

### Compute Engine

hive3.1
flink1.16.2

### Minimal reproduce step
```
CREATE CATALOG catalog_paimon WITH (
'type' = 'paimon',
'metastore' = 'hive',
'uri' = 'thrift://master.medatc:9083',
'warehouse' = 'hdfs:///flink/warehouse/'
);

drop table if exists catalog_paimon.ods_flink_data.dw_v_skds_equipment_basic_info;
CREATE TABLE catalog_paimon.ods_flink_data.dw_v_skds_equipment_basic_info(
`organization_code` string, 
`eid` string, 
`equipment_location` string, 
`diagnosis_operator_quantity` int,
primary key(organization_code,eid) not enforced
) with (
'merge-engine' = 'partial-update',
'bucket' = '1'
);

-- flink cli
insert into catalog_paimon.ods_flink_data.dw_v_skds_equipment_basic_info
values('1','2','2楼',3);

-- hive cli (fail)
insert into ods_flink_data.dw_v_skds_equipment_basic_info
values('1','2','3楼',4);
```
### What doesn't meet your expectations?
```
2024-01-29 02:53:58,269 [ERROR] [Dispatcher thread {Central}] |impl.DAGImpl|: Commit failed for output: outputName:MROutput of vertex/vertexGroup:initialmap isVertexGroupOutput:false, java.lan
g.RuntimeException: Can not read or parse CommitMessage file: hdfs://master.medatc:8020/flink/warehouse/ods_flink_data.db/dw_v_skds_equipment_basic_info/temp/job_1695283735910_0639/task_0.preC
ommit
        at org.apache.paimon.hive.mapred.PaimonOutputCommitter.readPreCommitFile(PaimonOutputCommitter.java:274)
        at org.apache.paimon.hive.mapred.PaimonOutputCommitter.getAllPreCommitMessage(PaimonOutputCommitter.java:223)
        at org.apache.paimon.hive.mapred.PaimonOutputCommitter.commitJob(PaimonOutputCommitter.java:143)
        at org.apache.hadoop.mapred.OutputCommitter.commitJob(OutputCommitter.java:291)
        at org.apache.tez.mapreduce.committer.MROutputCommitter.commitOutput(MROutputCommitter.java:99)
        at org.apache.tez.dag.app.dag.impl.DAGImpl$1.run(DAGImpl.java:1066)
        at org.apache.tez.dag.app.dag.impl.DAGImpl$1.run(DAGImpl.java:1063)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.tez.dag.app.dag.impl.DAGImpl.commitOutput(DAGImpl.java:1063)
        at org.apache.tez.dag.app.dag.impl.DAGImpl.access$2100(DAGImpl.java:153)
        at org.apache.tez.dag.app.dag.impl.DAGImpl$3.call(DAGImpl.java:1142)
        at org.apache.tez.dag.app.dag.impl.DAGImpl$3.call(DAGImpl.java:1137)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Alibaba-HZY** [comment]
tez  is not supported please use hive on mr

**Comment by www2388258980** [comment]
> insert into ods_flink_data.dw_v_skds_equipment_basic_info
> values('1','2','3楼',4);

**Comment by www2388258980** [comment]
> insert into ods_flink_data.dw_v_skds_equipment_basic_info
> values('1','2','3楼',4);



> tez is not supported please use hive on mr

**Comment by www2388258980** [comment]
> tez is not supported please use hive on mr

use mr;
set hive.execution.engine=mr;

**Comment by www2388258980** [comment]
Although the task is intended to be executed as an MR (MapReduce) job, it is currently utilizing Tez to generate the execution plan. To ensure that the job runs on the traditional MapReduce framework instead of Tez, you need to modify the mapreduce.framework.name property in the mapred-site.xml configuration file from yarn-tez to yarn. Subsequently, you would restart the hive-server2 service for these changes to take effect.
