### ISSUE TITLE
[Bug] DeleteFromPaimonTableCommand in paimon-spark-common is no compatable with paimon-spark-3.x (x<3)

### ISSUE THREAD

**Issue by nonggialiang** [apache/incubator-paimon#2860]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6

### Compute Engine

spark 3.2.1

### Minimal reproduce step

use paimon-spark-3.2-0.6-incubating.jar for spark3.2  
and run a "delete from" sql on a paimon table

### What doesn't meet your expectations?

Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.plans.logical.DeleteFromTable.condition()Lorg/apache/spark/sql/catalyst/expressions/Expression;
        at org.apache.paimon.spark.commands.DeleteFromPaimonTableCommand.<init>(DeleteFromPaimonTableCommand.scala:46) ~[paimon-spark-3.2-0.6-SNAPSHOT.jar:0.6-SNAPSHOT]
        at org.apache.paimon.spark.catalyst.analysis.PaimonDeleteTable$$anonfun$apply$1.applyOrElse(PaimonDeleteTable.scala:34) ~[paimon-spark-3.2-0.6-SNAPSHOT.jar:0.6-SNAPSHOT]
        at org.apache.paimon.spark.catalyst.analysis.PaimonDeleteTable$$anonfun$apply$1.applyOrElse(PaimonDeleteTable.scala:30) ~[paimon-spark-3.2-0.6-SNAPSHOT.jar:0.6-SNAPSHOT]
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$2(AnalysisHelper.scala:170) ~[spark-catalyst_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82) ~[spark-catalyst_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:170) ~[spark-catalyst_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323) ~[spark-catalyst_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:168) ~[spark-catalyst_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164) ~[spark-catalyst_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:30) ~[spark-catalyst_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning(AnalysisHelper.scala:99) ~[spark-catalyst_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning$(AnalysisHelper.scala:96) ~[spark-catalyst_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsWithPruning(LogicalPlan.scala:30) ~[spark-catalyst_2.12-3.2.1.jar:3.2.1]

### Anything else?

These codes may have similar problem:  
PaimonScanBuilder (with SupportsPushDownLimit)  
ExpressionHelper (using DataType.equalsIgnoreCaseAndNullability)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by choucmei** [comment]
Because the DeleteFromTable conditions in Spark 3.3 are required.
 https://github.com/apache/spark/pull/35941/files#diff-594addaa7ed3dd43fd0dad5fa81ade5ec2e570adf7c982c0570e3358a08a8e0a.
 Please assign this bug to me .
