### ISSUE TITLE
[Bug] Unable to create database/table path

### ISSUE THREAD

**Issue by andreale28** [apache/incubator-paimon#2874]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.7-incubating

### Compute Engine

Flink 1.18.0, Hive Metastore 3.1.3

### Minimal reproduce step

At first, I can create and use paimon catalog successfully
```
create catalog test2
 with ( 'type'='paimon',
     'metastore'='hive',
     'hive-conf-dir'='hive-conf',
     'location-in-properties'='true');

use catalog test2;
```
However when I execute `create database abc`, SQL-client returns this error:
`[ERROR] Could not execute SQL statement. Reason:
MetaException(message:Unable to create database path file:/user/hive/warehouse/abc.db, failed to create database abc)
`
This is the message in log file
```
Caused by: MetaException(message:Unable to create database path file:/user/hive/warehouse/abc.db, failed to create database abc)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result$create_database_resultStandardScheme.read(ThriftHiveMetastore.java:39343)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result$create_database_resultStandardScheme.read(ThriftHiveMetastore.java:39311)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result.read(ThriftHiveMetastore.java:39245)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_database(ThriftHiveMetastore.java:1106)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_database(ThriftHiveMetastore.java:1093)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createDatabase(HiveMetaStoreClient.java:811)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:208)
	at com.sun.proxy.$Proxy43.createDatabase(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2775)
	at com.sun.proxy.$Proxy44.createDatabase(Unknown Source)
	at org.apache.paimon.hive.HiveCatalog.createDatabaseImpl(HiveCatalog.java:233)
	... 19 more
```
Additionally, this is my `hive-site.xml` config:
```
<configuration>
    <property>
        <name>hive.metastore.uris</name>
        <value>thrift://metastore:9083</value>
        <description>Thrift URI for the remote metastore. Used by metastore client to connect to remote metastore.
        </description>
    </property>
    <property>
        <name>metastore.task.threads.always</name>
        <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>
    </property>
    <property>
        <name>metastore.expression.proxy</name>
        <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
    </property>

    <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>s3://paimonmetastore/warehouse</value>
    </property>

    <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
    </property>

    <!--    <property>-->
    <!--        <name>javax.jdo.option.ConnectionURL</name>-->
    <!--        <value>jdbc:mysql://mariadb:3306/metadatadb</value>-->
    <!--    </property>-->
    <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://metadata:5432/metadatadb</value>
    </property>

    <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>sonle</value>
    </property>

    <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>sonle123</value>
    </property>

    <property>
        <name>fs.s3a.access.key</name>
        <value>minio</value>
    </property>
    <property>
        <name>fs.s3a.secret.key</name>
        <value>minio123</value>
    </property>
    <property>
        <name>fs.s3a.endpoint</name>
        <value>http://minio:9000</value>
    </property>
    <property>
        <name>fs.s3a.path.style.access</name>
        <value>true</value>
    </property>
    <property>
        <name>fs.s3a.impl</name>
        <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
    </property>


</configuration>
```

### What doesn't meet your expectations?

I looks like there is a bug in either paimon or hive. Since I'm not expertise in Java, I would ask here to have more context to debug my problem.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by andreale28** [comment]
additional log message
```
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: Unable to create database path file:/user/hive/warehouse/abc.db, failed to create database abc
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result$create_database_resultStandardScheme.read(ThriftHiveMetastore.java:39343) ~[flink-sql-connector-hive-3.1.3_2.12-1.18.0.jar:1.18.0]
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result$create_database_resultStandardScheme.read(ThriftHiveMetastore.java:39311) ~[flink-sql-connector-hive-3.1.3_2.12-1.18.0.jar:1.18.0]
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result.read(ThriftHiveMetastore.java:39245) ~[flink-sql-connector-hive-3.1.3_2.12-1.18.0.jar:1.18.0]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86) ~[flink-sql-connector-hive-3.1.3_2.12-1.18.0.jar:1.18.0]
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_database(ThriftHiveMetastore.java:1106) ~[flink-sql-connector-hive-3.1.3_2.12-1.18.0.jar:1.18.0]
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_database(ThriftHiveMetastore.java:1093) ~[flink-sql-connector-hive-3.1.3_2.12-1.18.0.jar:1.18.0]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createDatabase(HiveMetaStoreClient.java:811) ~[flink-sql-connector-hive-3.1.3_2.12-1.18.0.jar:1.18.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:208) ~[flink-sql-connector-hive-3.1.3_2.12-1.18.0.jar:1.18.0]
	at com.sun.proxy.$Proxy43.createDatabase(Unknown Source) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2775) ~[flink-sql-connector-hive-3.1.3_2.12-1.18.0.jar:1.18.0]
	at com.sun.proxy.$Proxy44.createDatabase(Unknown Source) ~[?:?]
	at org.apache.paimon.hive.HiveCatalog.createDatabaseImpl(HiveCatalog.java:233) ~[paimon-flink-1.18-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.paimon.catalog.AbstractCatalog.createDatabase(AbstractCatalog.java:108) ~[paimon-flink-1.18-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.paimon.catalog.Catalog.createDatabase(Catalog.java:80) ~[paimon-flink-1.18-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.paimon.flink.FlinkCatalog.createDatabase(FlinkCatalog.java:209) ~[paimon-flink-1.18-0.7.0-incubating.jar:0.7.0-incubating]
	at org.apache.flink.table.catalog.CatalogManager.createDatabase(CatalogManager.java:1381) ~[flink-table-api-java-uber-1.18.0.jar:1.18.0]
	at org.apache.flink.table.operations.ddl.CreateDatabaseOperation.execute(CreateDatabaseOperation.java:84) ~[flink-table-api-java-uber-1.18.0.jar:1.18.0]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1092) ~[flink-table-api-java-uber-1.18.0.jar:1.18.0]
	at org.apache.flink.table.gateway.service.operation.OperationExecutor.callOperation(OperationExecutor.java:556) ~[flink-sql-gateway-1.18.0.jar:1.18.0]
	at org.apache.flink.table.gateway.service.operation.OperationExecutor.executeOperation(OperationExecutor.java:444) ~[flink-sql-gateway-1.18.0.jar:1.18.0]
	at org.apache.flink.table.gateway.service.operation.OperationExecutor.executeStatement(OperationExecutor.java:207) ~[flink-sql-gateway-1.18.0.jar:1.18.0]
	at org.apache.flink.table.gateway.service.SqlGatewayServiceImpl.lambda$executeStatement$1(SqlGatewayServiceImpl.java:212) ~[flink-sql-gateway-1.18.0.jar:1.18.0]
	at org.apache.flink.table.gateway.service.operation.OperationManager.lambda$submitOperation$1(OperationManager.java:119) ~[flink-sql-gateway-1.18.0.jar:1.18.0]
	at org.apache.flink.table.gateway.service.operation.OperationManager$Operation.lambda$run$0(OperationManager.java:258) ~[flink-sql-gateway-1.18.0.jar:1.18.0]
	... 7 more
```

**Comment by herefree** [comment]
@andreale28 It looks like a permissions issue，you can try it https://stackoverflow.com/questions/15898211/unable-to-create-database-path-file-user-hive-warehouse-error

**Comment by andreale28** [comment]
it turns out there is a bug in my docker, resolved this issue.

**Comment by longpt233** [comment]
hi @andreale28 , a have same issue liked you with docker. can you describe  your bug and how did you fix this ? thank you
