### ISSUE TITLE
[Bug] BatchTableWrite cannot use in Multithreading

### ISSUE THREAD

**Issue by Pandas886** [apache/incubator-paimon#2896]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6.1

### Compute Engine

java api

### Minimal reproduce step

When I execute the following code multiple times, an error occurs.

```
Catalog catalog = createFilesystemCatalog();

        // 1. Create a WriteBuilder (Serializable)
        Table table = catalog.getTable(Identifier.create("my_db", "my_table"));

        BatchWriteBuilder writeBuilder = table.newBatchWriteBuilder();

        List<CommitMessage> messageList = new CopyOnWriteArrayList<>();
        List<Thread> threads = new ArrayList<>();
        for (int i = 0; i < 4; i++) {
            int finalI = i;
            Thread thread = new Thread(() -> {
                // 2. Write records in distributed tasks
                BatchTableWrite write = writeBuilder.newWrite();
                GenericRow record1 = GenericRow.of(BinaryString.fromString("Alice-" + finalI), 12+finalI);
                GenericRow record2 = GenericRow.of(BinaryString.fromString("Bob-" + finalI), 5+finalI);
                GenericRow record3 = GenericRow.of(BinaryString.fromString("Emily-" + finalI), 18+finalI);

                try {
                    write.write(record1);
                    write.write(record2);
                    write.write(record3);
                    List<CommitMessage> messages = write.prepareCommit();
                    messageList.addAll(messages);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }

            });
            thread.start();
            threads.add(thread);
        }

        for (Thread thread : threads) {
            thread.join();
        }

        // 3. Collect all CommitMessages to a global node and commit
        BatchTableCommit commit = writeBuilder.newCommit();
        commit.commit(messageList);

```

my table schema.
![image](https://github.com/apache/incubator-paimon/assets/123344357/b1e853a0-c844-4e1b-b334-d97d15e50cc8)

The first time it runs fine, but an error occurs the second time.

```
Exception in thread "main" java.lang.RuntimeException: File deletion conflicts detected! Give up committing.

Don't panic!
Conflicts during commits are normal and this failure is intended to resolve the conflicts.
Conflicts are mainly caused by the following scenarios:
1. Your job is suffering from back-pressuring.
   There are too many snapshots waiting to be committed and an exception occurred during the commit procedure (most probably due to checkpoint timeout).
   See https://paimon.apache.org/docs/master/maintenance/write-performance/ for how to improve writing performance.
2. Multiple jobs are writing into the same partition at the same time, or you use STATEMENT SET to execute multiple INSERT statements into the same Paimon table.
   You'll probably see different base commit user and current commit user below.
   You can use https://paimon.apache.org/docs/master/maintenance/dedicated-compaction#dedicated-compaction-jobto support multiple writing.
3. You're recovering from an old savepoint, or you're creating multiple jobs from a savepoint.
   The job will fail continuously in this scenario to protect metadata from corruption.
   You can either recover from the latest savepoint, or you can revert the table to the snapshot corresponding to the old savepoint.

Base commit user is: f8209f9d-d9f5-4c33-b079-54fcbae77a78; Current commit user is: b2c0ed24-b63b-462c-bdd2-2159ec9bbd9f

Base entries are:
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-78288c3f-2e34-492e-889e-197a13021b29-0.orc, 616, 3, org.apache.paimon.data.BinaryRow@32323de8, org.apache.paimon.data.BinaryRow@86fe5854, org.apache.paimon.stats.BinaryTableStats@c7678a92, org.apache.paimon.stats.BinaryTableStats@e2c821ea, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-92d48806-255f-4f26-8195-c7c94f5aa26c-0.orc, 624, 3, org.apache.paimon.data.BinaryRow@eb3f5e0d, org.apache.paimon.data.BinaryRow@ad98ad44, org.apache.paimon.stats.BinaryTableStats@1e5d7e87, org.apache.paimon.stats.BinaryTableStats@a937d947, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-34f46ae6-92b0-4c11-8167-4a8fe48ce52a-0.orc, 620, 3, org.apache.paimon.data.BinaryRow@3985af88, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@8fdb9e08, org.apache.paimon.stats.BinaryTableStats@249999b6, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-0faf9dc3-a4ff-4916-9736-86bd64cb5432-0.orc, 620, 3, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@5b7b7d64, org.apache.paimon.stats.BinaryTableStats@4c087f8e, org.apache.paimon.stats.BinaryTableStats@931b919e, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-11f5c5c9-d79b-4518-b4b6-044eba8102c9-0.orc, 622, 3, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@5b7b7d64, org.apache.paimon.stats.BinaryTableStats@4c087f8e, org.apache.paimon.stats.BinaryTableStats@931b919e, 3, 5, 0, 0, [], 2024-02-23T16:57:09.887}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-60b27a8a-78b6-49fb-8fc2-9fb458da35ac-0.orc, 622, 3, org.apache.paimon.data.BinaryRow@3985af88, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@8fdb9e08, org.apache.paimon.stats.BinaryTableStats@249999b6, 3, 5, 0, 0, [], 2024-02-23T16:57:09.887}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-dfb86a81-c754-4d3e-a879-9d529fc3466a-0.orc, 618, 3, org.apache.paimon.data.BinaryRow@32323de8, org.apache.paimon.data.BinaryRow@86fe5854, org.apache.paimon.stats.BinaryTableStats@c7678a92, org.apache.paimon.stats.BinaryTableStats@e2c821ea, 3, 5, 0, 0, [], 2024-02-23T16:57:09.887}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-e561a33d-90ee-4708-ac5c-4405c179269c-0.orc, 626, 3, org.apache.paimon.data.BinaryRow@eb3f5e0d, org.apache.paimon.data.BinaryRow@ad98ad44, org.apache.paimon.stats.BinaryTableStats@1e5d7e87, org.apache.paimon.stats.BinaryTableStats@a937d947, 3, 5, 0, 0, [], 2024-02-23T16:57:09.887}}

Changes are:
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-11f5c5c9-d79b-4518-b4b6-044eba8102c9-0.orc, 622, 3, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@5b7b7d64, org.apache.paimon.stats.BinaryTableStats@4c087f8e, org.apache.paimon.stats.BinaryTableStats@931b919e, 3, 5, 0, 0, [], 2024-02-23T16:57:09.887}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-0faf9dc3-a4ff-4916-9736-86bd64cb5432-0.orc, 620, 3, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@5b7b7d64, org.apache.paimon.stats.BinaryTableStats@4c087f8e, org.apache.paimon.stats.BinaryTableStats@931b919e, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-92d48806-255f-4f26-8195-c7c94f5aa26c-0.orc, 624, 3, org.apache.paimon.data.BinaryRow@eb3f5e0d, org.apache.paimon.data.BinaryRow@ad98ad44, org.apache.paimon.stats.BinaryTableStats@1e5d7e87, org.apache.paimon.stats.BinaryTableStats@a937d947, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-34f46ae6-92b0-4c11-8167-4a8fe48ce52a-0.orc, 620, 3, org.apache.paimon.data.BinaryRow@3985af88, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@8fdb9e08, org.apache.paimon.stats.BinaryTableStats@249999b6, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-78288c3f-2e34-492e-889e-197a13021b29-0.orc, 616, 3, org.apache.paimon.data.BinaryRow@32323de8, org.apache.paimon.data.BinaryRow@86fe5854, org.apache.paimon.stats.BinaryTableStats@c7678a92, org.apache.paimon.stats.BinaryTableStats@e2c821ea, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-1d8c45ee-8f52-469a-9516-df37ba06bdbc-0.orc, 692, 12, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@d9178c74, org.apache.paimon.stats.BinaryTableStats@e94f44c0, 0, 5, 0, 5, [], 2024-02-23T16:57:10.035}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-0faf9dc3-a4ff-4916-9736-86bd64cb5432-0.orc, 620, 3, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@5b7b7d64, org.apache.paimon.stats.BinaryTableStats@4c087f8e, org.apache.paimon.stats.BinaryTableStats@931b919e, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-78288c3f-2e34-492e-889e-197a13021b29-0.orc, 616, 3, org.apache.paimon.data.BinaryRow@32323de8, org.apache.paimon.data.BinaryRow@86fe5854, org.apache.paimon.stats.BinaryTableStats@c7678a92, org.apache.paimon.stats.BinaryTableStats@e2c821ea, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-60b27a8a-78b6-49fb-8fc2-9fb458da35ac-0.orc, 622, 3, org.apache.paimon.data.BinaryRow@3985af88, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@8fdb9e08, org.apache.paimon.stats.BinaryTableStats@249999b6, 3, 5, 0, 0, [], 2024-02-23T16:57:09.887}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-34f46ae6-92b0-4c11-8167-4a8fe48ce52a-0.orc, 620, 3, org.apache.paimon.data.BinaryRow@3985af88, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@8fdb9e08, org.apache.paimon.stats.BinaryTableStats@249999b6, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-92d48806-255f-4f26-8195-c7c94f5aa26c-0.orc, 624, 3, org.apache.paimon.data.BinaryRow@eb3f5e0d, org.apache.paimon.data.BinaryRow@ad98ad44, org.apache.paimon.stats.BinaryTableStats@1e5d7e87, org.apache.paimon.stats.BinaryTableStats@a937d947, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-23a67aa8-9f7e-4f81-9609-bd7f484aa617-0.orc, 692, 12, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@d9178c74, org.apache.paimon.stats.BinaryTableStats@e94f44c0, 0, 5, 0, 5, [], 2024-02-23T16:57:10.040}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-0faf9dc3-a4ff-4916-9736-86bd64cb5432-0.orc, 620, 3, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@5b7b7d64, org.apache.paimon.stats.BinaryTableStats@4c087f8e, org.apache.paimon.stats.BinaryTableStats@931b919e, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-78288c3f-2e34-492e-889e-197a13021b29-0.orc, 616, 3, org.apache.paimon.data.BinaryRow@32323de8, org.apache.paimon.data.BinaryRow@86fe5854, org.apache.paimon.stats.BinaryTableStats@c7678a92, org.apache.paimon.stats.BinaryTableStats@e2c821ea, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-92d48806-255f-4f26-8195-c7c94f5aa26c-0.orc, 624, 3, org.apache.paimon.data.BinaryRow@eb3f5e0d, org.apache.paimon.data.BinaryRow@ad98ad44, org.apache.paimon.stats.BinaryTableStats@1e5d7e87, org.apache.paimon.stats.BinaryTableStats@a937d947, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-34f46ae6-92b0-4c11-8167-4a8fe48ce52a-0.orc, 620, 3, org.apache.paimon.data.BinaryRow@3985af88, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@8fdb9e08, org.apache.paimon.stats.BinaryTableStats@249999b6, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-dfb86a81-c754-4d3e-a879-9d529fc3466a-0.orc, 618, 3, org.apache.paimon.data.BinaryRow@32323de8, org.apache.paimon.data.BinaryRow@86fe5854, org.apache.paimon.stats.BinaryTableStats@c7678a92, org.apache.paimon.stats.BinaryTableStats@e2c821ea, 3, 5, 0, 0, [], 2024-02-23T16:57:09.887}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-0ae6eb0b-5520-4473-b9d5-43d61ad2434c-0.orc, 685, 12, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@d9178c74, org.apache.paimon.stats.BinaryTableStats@e94f44c0, 0, 5, 0, 5, [], 2024-02-23T16:57:10.048}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-0faf9dc3-a4ff-4916-9736-86bd64cb5432-0.orc, 620, 3, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@5b7b7d64, org.apache.paimon.stats.BinaryTableStats@4c087f8e, org.apache.paimon.stats.BinaryTableStats@931b919e, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-78288c3f-2e34-492e-889e-197a13021b29-0.orc, 616, 3, org.apache.paimon.data.BinaryRow@32323de8, org.apache.paimon.data.BinaryRow@86fe5854, org.apache.paimon.stats.BinaryTableStats@c7678a92, org.apache.paimon.stats.BinaryTableStats@e2c821ea, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-92d48806-255f-4f26-8195-c7c94f5aa26c-0.orc, 624, 3, org.apache.paimon.data.BinaryRow@eb3f5e0d, org.apache.paimon.data.BinaryRow@ad98ad44, org.apache.paimon.stats.BinaryTableStats@1e5d7e87, org.apache.paimon.stats.BinaryTableStats@a937d947, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-34f46ae6-92b0-4c11-8167-4a8fe48ce52a-0.orc, 620, 3, org.apache.paimon.data.BinaryRow@3985af88, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@8fdb9e08, org.apache.paimon.stats.BinaryTableStats@249999b6, 0, 2, 0, 0, [], 2024-02-23T16:56:54.072}}
{DELETE, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-e561a33d-90ee-4708-ac5c-4405c179269c-0.orc, 626, 3, org.apache.paimon.data.BinaryRow@eb3f5e0d, org.apache.paimon.data.BinaryRow@ad98ad44, org.apache.paimon.stats.BinaryTableStats@1e5d7e87, org.apache.paimon.stats.BinaryTableStats@a937d947, 3, 5, 0, 0, [], 2024-02-23T16:57:09.887}}
{ADD, org.apache.paimon.data.BinaryRow@9c67b85d, 0, 1, {data-39d7c76d-0061-4c61-b0ba-448827e7f8ba-0.orc, 685, 12, org.apache.paimon.data.BinaryRow@f8248f4, org.apache.paimon.data.BinaryRow@4f843bbe, org.apache.paimon.stats.BinaryTableStats@d9178c74, org.apache.paimon.stats.BinaryTableStats@e94f44c0, 0, 5, 0, 5, [], 2024-02-23T16:57:10.058}}
	at org.apache.paimon.operation.FileStoreCommitImpl.createConflictException(FileStoreCommitImpl.java:1011)
	at org.apache.paimon.operation.FileStoreCommitImpl.noConflictsOrFail(FileStoreCommitImpl.java:907)
	at org.apache.paimon.operation.FileStoreCommitImpl.commit(FileStoreCommitImpl.java:265)
	at org.apache.paimon.table.sink.TableCommitImpl.commitMultiple(TableCommitImpl.java:199)
	at org.apache.paimon.table.sink.TableCommitImpl.commit(TableCommitImpl.java:193)
	at org.apache.paimon.table.sink.TableCommitImpl.commit(TableCommitImpl.java:172)
	at org.apache.paimon.table.sink.TableCommitImpl.commit(TableCommitImpl.java:167)
	at org.apache.seatunnel.connectors.seatunnel.paimon.utils.PaimonWriteTest.main(PaimonWriteTest.java:71)
Caused by: java.lang.IllegalStateException: Trying to delete file data-0faf9dc3-a4ff-4916-9736-86bd64cb5432-0.orc which is not previously added. Manifest might be corrupted.
	at org.apache.paimon.utils.Preconditions.checkState(Preconditions.java:204)
	at org.apache.paimon.manifest.ManifestEntry.assertNoDelete(ManifestEntry.java:182)
	at org.apache.paimon.operation.FileStoreCommitImpl.noConflictsOrFail(FileStoreCommitImpl.java:904)
	... 6 more
```

### What doesn't meet your expectations?

run without error

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Hi @Pandas886 , please take a look to the exception stack, the exception is from `TableCommit.commit`. Please take a look to https://paimon.apache.org/docs/master/maintenance/dedicated-compaction/

**Comment by Pandas886** [comment]
> Hi @Pandas886 , please take a look to the exception stack, the exception is from `TableCommit.commit`. Please take a look to https://paimon.apache.org/docs/master/maintenance/dedicated-compaction/

Hi @JingsongLi I hope to develop a Presto connector and a SeaTunnel connector using BatchTableWrite. If write-only=true is the only option, the connector will not be able to support tables without the write-only attribute. My expectation is that the SeaTunnel connector can write to the Paimon table and also support tables without the write-only attribute like the Flink Paimon connector.

**Comment by JingsongLi** [comment]
> > Hi @Pandas886 , please take a look to the exception stack, the exception is from `TableCommit.commit`. Please take a look to https://paimon.apache.org/docs/master/maintenance/dedicated-compaction/
> 
> Hi @JingsongLi I hope to develop a Presto connector and a SeaTunnel connector using BatchTableWrite. If write-only=true is the only option, the connector will not be able to support tables without the write-only attribute. My expectation is that the SeaTunnel connector can write to the Paimon table and also support tables without the write-only attribute like the Flink Paimon connector.

Yes, you can, just keep only one thread to commit, then OK
