### ISSUE TITLE
[Bug] SELECT SQL with OPTIONS throws SqlParseException 

### ISSUE THREAD

**Issue by rmotapar** [apache/incubator-paimon#2973]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.7.0-incubating

### Compute Engine

Flink

### Minimal reproduce step

Per [documentation](https://paimon.apache.org/docs/master/how-to/querying-tables/#consumer-id), to set 'consumer-id' we need to add `/*+ OPTIONS('consumer-id' = 'example-consumer-id') */` at the end of the Select SQL. 

1. A simple Flink java job that selects from a Paimon table with 'consumer-id' option:
   ```
   final StreamTableEnvironment tableEnv = StreamTableEnvironment.create(env);
   String selectSql = "SELECT * FROM PAIMON_TABLE /*+ OPTIONS('consumer-id' = 'paimonTableConsumer') */ ;";
   Table source = tableEnv.sqlQuery(queryFromPaimonSQL);
   ...
   ```
  
2.  Running the program throws SqlParseException as shown below:
```
Exception in thread "main" org.apache.flink.table.api.SqlParserException: SQL parse failed. Encountered "/*+" at line 2, column 64.
Was expecting one of:
    <EOF> 
    "EXCEPT" ...
    "FETCH" ...
....
....
at org.apache.flink.table.planner.parse.CalciteParser.parseSqlList(CalciteParser.java:81)
	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:102)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.sqlQuery(TableEnvironmentImpl.java:708)


```

   

### What doesn't meet your expectations?

Unable to set consumer-id option or any other table options on a SELECT SQL

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by rmotapar** [comment]
Please ignore this. I realized my mistake. I was adding `/*+ OPTIONS ...` after the WHERE clause in the SELECT SQL. This is what was causing the SqlParseException. I tried adding `/*+ OPTIONS ...` before the WHERE clause and AFTER the FROM and it worked as expected.
