### ISSUE TITLE
[Bug] FlinkActionsE2eTest.testDelete is unstable

### ISSUE THREAD

**Issue by FangYongs** [apache/incubator-paimon#657]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

https://github.com/apache/incubator-paimon/actions/runs/4465175758/jobs/7841980086?pr=656

Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 265.233 s <<< FAILURE! - in org.apache.paimon.tests.FlinkActionsE2eTest
Error:  testDelete  Time elapsed: 110.359 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Result is still unexpected after 60 retries.
Expected: {2023-01-21, 1, 31=1, 2023-01-20, 1, 28=1, 2023-01-19, 1, 23=1, 2023-01-18, 1, 75=1, 2023-01-17, 1, 50=1}
Actual: {2023-01-21, 1, 31=1, 2023-01-14, 0, 19=1, 2023-01-13, 0, 39=1, 2023-01-16, 1, 25=1, 2023-01-15, 0, 37=1, 2023-01-20, 1, 28=1, 2023-01-19, 1, 23=1, 2023-01-18, 1, 75=1, 2023-01-17, 1, 50=1}
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at org.apache.paimon.tests.E2eTestBase.checkResult(E2eTestBase.java:261)
	at org.apache.paimon.tests.FlinkActionsE2eTest.testDelete(FlinkActionsE2eTest.java:[256](https://github.com/apache/incubator-paimon/actions/runs/4465175758/jobs/7841980086?pr=656#step:5:257))
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)

### Compute Engine

flink

### Minimal reproduce step

no

### What doesn't meet your expectations?

no

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by FangYongs** [comment]
Thanks @liyubin117, assigned
