### ISSUE TITLE
[Bug] Dependency issues using kafka as a external log system

### ISSUE THREAD

**Issue by golden-yang** [apache/incubator-paimon#803]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

paimon version: paimon-flink-1.16-0.4-20230331.003039-13.jar

### Compute Engine

flink 1.16.1

### Minimal reproduce step

Learning from this [PR](https://github.com/apache/incubator-paimon/pull/729). We should add flink-connetor-kafka-\*.jar and kafka-clients-\*.jar to flink lib directory, before we use kafka as external log systems.

# test 1
add these jar file to lib directory:

/opt/flink-1.16.1]# ls lib/ | grep kafka
- flink-connector-kafka-1.16.1.jar
- kafka-clients-2.8.1.jar

Insert data in sql client.  **It looks like only flink-connector-kafka does not meet dependency requirements.**
`
INSERT INTO changelog_kafka_input values('hello', 1, 1);

[INFO] Submitting SQL update statement to the cluster...
[ERROR] Could not execute SQL statement. Reason:
java.lang.ClassNotFoundException: org.apache.flink.kafka.shaded.org.apache.kafka.clients.producer.ProducerRecord
`

`
Caused by: java.lang.ClassNotFoundException: org.apache.flink.kafka.shaded.org.apache.kafka.clients.consumer.ConsumerRecord
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
`

# test 2
Add these jar file to lib directory. This time I add `flink-sql-connector-kafka-1.16.1.jar`.

/opt/flink-1.16.1]# ls lib/ | grep kafka
- flink-connector-kafka-1.16.1.jar
- flink-sql-connector-kafka-1.16.1.jar
- kafka-clients-2.8.1.jar

Insert data in sql client.  **It seems that flink-connector-kafka and flink-connector-sql-kafka will have package conflicts in paimon. **  I saw some related fixes in this [pr 260](https://github.com/apache/incubator-paimon/pull/260/files).

`
Caused by: java.lang.AbstractMethodError: Method org/apache/paimon/flink/kafka/KafkaLogDeserializationSchema.deserialize(Lorg/apache/kafka/clients/consumer/ConsumerRecord;)Ljava/lang/Object; is abstract
	at org.apache.paimon.flink.kafka.KafkaLogDeserializationSchema.deserialize(KafkaLogDeserializationSchema.java)
	at org.apache.flink.streaming.connectors.kafka.KafkaDeserializationSchema.deserialize(KafkaDeserializationSchema.java:79)
	at org.apache.flink.connector.kafka.source.reader.deserializer.KafkaDeserializationSchemaWrapper.deserialize(KafkaDeserializationSchemaWrapper.java:54)
	at org.apache.flink.connector.kafka.source.reader.KafkaRecordEmitter.emitRecord(KafkaRecordEmitter.java:53)
	at org.apache.flink.connector.kafka.source.reader.KafkaRecordEmitter.emitRecord(KafkaRecordEmitter.java:33)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:143)
	at org.apache.flink.connector.base.source.hybrid.HybridSourceReader.pollNext(HybridSourceReader.java:85)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:385)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:542)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:831)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:780)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:935)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:914)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:728)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:550)
	at java.lang.Thread.run(Thread.java:750)
`

# test 3
add these jar file to lib directory:

/opt/flink-1.16.1]# ls lib/ | grep kafka
- flink-sql-connector-kafka-1.16.1.jar
- kafka-clients-2.8.1.jar

Insert data and query data will success in sql client.

### What doesn't meet your expectations?

- [ ] 1. We should preferably indicate in the document which jars need to be added, when using kafka as external log systems.

- [x] 2. Makes me confused which dependency should I use. Confirm that using the following two jar packages is the correct choice?
- flink-sql-connector-kafka-1.16.1.jar
- kafka-clients-2.8.1.jar

- [x] 3. It seems that flink-connector-kafka and flink-connector-sql-kafka will have package conflicts in paimon. 
- flink-connector-kafka-1.16.1.jar
- flink-sql-connector-kafka-1.16.1.jar

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Alibaba-HZY** [comment]
This bug is similar to https://github.com/apache/incubator-paimon/issues/705
Will be fixed in this pr https://github.com/apache/incubator-paimon/pull/771

**Comment by Alibaba-HZY** [comment]
sorry in this pr,my description is not accurate enough,i'm going to modify the description,you just add flink-sql-connector-kafka-*.jar in your lib
this is problem will be fixed in this pr https://github.com/apache/incubator-paimon/pull/771

**Comment by golden-yang** [comment]
> sorry in this pr #729 ,my description is not accurate enough,i'm going to modify the description,you just add flink-sql-connector-kafka-_.jar in your lib you don't need to add kafka-clients-2.8.1.jar because flink-sql-connector-kafka-_.jar contains it this is problem will be fixed in this pr #771


@Alibaba-HZY   thanks for you reply. Question 2 and question 3 are solved.
Should we add these dependencies to the docment?

**Comment by Alibaba-HZY** [comment]
> > sorry in this pr #729 ,my description is not accurate enough,i'm going to modify the description,you just add flink-sql-connector-kafka-_.jar in your lib you don't need to add kafka-clients-2.8.1.jar because flink-sql-connector-kafka-_.jar contains it this is problem will be fixed in this pr #771
> 
> @Alibaba-HZY thanks for you reply. Question 2 and question 3 are solved. Should we add these dependencies to the docment? also in this pr  https://github.com/apache/incubator-paimon/pull/771 ,it is not be merged

**Comment by golden-yang** [comment]
> > > sorry in this pr #729 ,my description is not accurate enough,i'm going to modify the description,you just add flink-sql-connector-kafka-_.jar in your lib you don't need to add kafka-clients-2.8.1.jar because flink-sql-connector-kafka-_.jar contains it this is problem will be fixed in this pr #771
> > 
> > 
> > @Alibaba-HZY thanks for you reply. Question 2 and question 3 are solved. Should we add these dependencies to the docment? also in this pr  #771 ,it is not be merged

OK, I missed that one. Thanks
