### ISSUE TITLE
[Bug]  CDC Ingestion   mysql  DATETIME(6) cast  error.

### ISSUE THREAD

**Issue by zhengshubin** [apache/incubator-paimon#860]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4-SNAPSHOT

### Compute Engine

flink 1.16  
paimon 0.1-SNAPSHOT  
mysql 8

### Minimal reproduce step

      MySqlSyncTableAction mySqlSyncTableAction = (MySqlSyncTableAction) action.get();
            StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
            env.setParallelism(4);
            env.enableCheckpointing(10000);
            env.setStateBackend(new HashMapStateBackend());

            mySqlSyncTableAction.build(env);
            env.execute(String.format("MySQL-Paimon Table Sync: %s.%s","flink","cdc_test"));

### What doesn't meet your expectations?

java.time.format.DateTimeParseException: Text '1649549400000000' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1777)
	at org.apache.paimon.utils.DateTimeUtils.parseTimestampData(DateTimeUtils.java:382)
	at org.apache.paimon.utils.TypeUtils.toTimestamp(TypeUtils.java:166)
	at org.apache.paimon.utils.TypeUtils.castFromString(TypeUtils.java:117)
	at org.apache.paimon.flink.sink.cdc.CdcRecord.toGenericRow(CdcRecord.java:119)
	at org.apache.paimon.flink.sink.cdc.SchemaAwareStoreWriteOperator.processRecord(SchemaAwareStoreWriteOperator.java:74)
	at org.apache.paimon.flink.sink.cdc.SchemaAwareStoreWriteOperator.processRecord(SchemaAwareStoreWriteOperator.java:45)
	at org.apache.paimon.flink.sink.AbstractStoreWriteOperator.processElement(AbstractStoreWriteOperator.java:123)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
CC @tsreaper

**Comment by zhengshubin** [comment]
If mysql  type is DATETIME(3) , it  also make error:
Exception in thread "main" java.time.format.DateTimeParseException: Text '2022-04-10 08:10' could not be parsed, unparsed text found at index 10
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1952)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1777)
	at org.apache.paimon.utils.DateTimeUtils.parseTimestampData(DateTimeUtils.java:382)
	at com.zsb.flink16.Event.main(Event.java:35)

**Comment by JingsongLi** [comment]
Thanks @zhengshubin ! Fixing is on the road!
