### ISSUE TITLE
[Bug] network xxx declared as external, but could not be found

### ISSUE THREAD

**Issue by schnappi17** [apache/incubator-paimon#874]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master: fb9babbb8676d598e817704db4993604b0d3a9d6

### Compute Engine

Flink 1.16

### Minimal reproduce step

1. start docker
2. set `rootLogger.level=INFO` in paimon-e2e-tests/src/test/resources/log4j2-test.properties
3. mvn test -D test=FileStoreBatchE2eTest

### What doesn't meet your expectations?

Run e2e test `FileStoreBatchE2eTest` will failed with the following exception: 

1487 [1 main] INFO  org.testcontainers.utility.ImageNameSubstitutor [] - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
1628 [1 main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy [] - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
3111 [1 main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy [] - Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
3112 [1 main] INFO  org.testcontainers.DockerClientFactory [] - Docker host IP address is localhost
3133 [1 main] INFO  org.testcontainers.DockerClientFactory [] - Connected to docker: 
  Server Version: 20.10.24
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 7859 MB
3167 [1 main] INFO  🐳 [testcontainers/ryuk:0.3.3] [] - Creating container for image: testcontainers/ryuk:0.3.3
3606 [1 main] INFO  🐳 [testcontainers/ryuk:0.3.3] [] - Container testcontainers/ryuk:0.3.3 is starting: e151c37133650ff45450e25a13b1284dd264c7d2fc0788a147916e3828ea9d7d
4075 [1 main] INFO  🐳 [testcontainers/ryuk:0.3.3] [] - Container testcontainers/ryuk:0.3.3 started in PT0.93S
4083 [1 main] INFO  org.testcontainers.utility.RyukResourceReaper [] - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
4083 [1 main] INFO  org.testcontainers.DockerClientFactory [] - Checking the system...
4084 [1 main] INFO  org.testcontainers.DockerClientFactory [] - ✔︎ Docker server version should be at least 1.6.0
4147 [1 main] INFO  org.testcontainers.containers.DockerComposeContainer [] - Preemptively checking local images for 'confluentinc/cp-zookeeper:7.0.1', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
4147 [1 main] INFO  org.testcontainers.containers.DockerComposeContainer [] - Preemptively checking local images for 'bde2020/hive:2.3.2-postgresql-metastore', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
4147 [1 main] INFO  org.testcontainers.containers.DockerComposeContainer [] - Preemptively checking local images for 'bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
4148 [1 main] INFO  org.testcontainers.containers.DockerComposeContainer [] - Preemptively checking local images for 'bde2020/hive-metastore-postgresql:2.3.0', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
4148 [1 main] INFO  org.testcontainers.containers.DockerComposeContainer [] - Preemptively checking local images for 'apache/flink:1.17.0-java8', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
4148 [1 main] INFO  org.testcontainers.containers.DockerComposeContainer [] - Preemptively checking local images for 'bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
4148 [1 main] INFO  org.testcontainers.containers.DockerComposeContainer [] - Preemptively checking local images for 'confluentinc/cp-kafka:7.0.1', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
4148 [1 main] INFO  org.testcontainers.containers.DockerComposeContainer [] - Preemptively checking local images for 'bde2020/spark-master:3.3.0-hadoop3.3', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
4149 [1 main] INFO  org.testcontainers.containers.DockerComposeContainer [] - Preemptively checking local images for 'bde2020/spark-worker:3.3.0-hadoop3.3', referenced via a compose file or transitive Dockerfile. If not available, it will be pulled.
4152 [1 main] INFO  🐳 [docker-compose] [] - Local Docker Compose is running command: up -d jobmanager taskmanager
4351 [22 Thread-4] INFO  🐳 [docker-compose] [] - **network 4b23a4cd8fc59e338e603387ce135d273d3dc53d8eb05bdad3c21429fa8e8b45 declared as external, but could not be found**
4367 [1 main] INFO  🐳 [docker-compose] [] - Local Docker Compose is running command: down -v
4535 [24 Thread-6] INFO  🐳 [docker-compose] [] -  Volume rr8q2w3rxawq_testdata  Removing
4536 [24 Thread-6] INFO  🐳 [docker-compose] [] -  Volume rr8q2w3rxawq_datanode  Removing
4536 [24 Thread-6] INFO  🐳 [docker-compose] [] -  Volume rr8q2w3rxawq_namenode  Removing
4540 [24 Thread-6] INFO  🐳 [docker-compose] [] -  Volume rr8q2w3rxawq_datanode  Removed
4542 [24 Thread-6] INFO  🐳 [docker-compose] [] -  Volume rr8q2w3rxawq_testdata  Removed
4547 [24 Thread-6] INFO  🐳 [docker-compose] [] -  Volume rr8q2w3rxawq_namenode  Removed
4561 [1 main] INFO  🐳 [docker-compose] [] - Docker Compose has finished running

org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 1 whilst running command: up -d jobmanager taskmanager

 at org.testcontainers.containers.LocalDockerCompose.invoke(DockerComposeContainer.java:771)
 at org.testcontainers.containers.DockerComposeContainer.runWithCompose(DockerComposeContainer.java:310)
 at org.testcontainers.containers.DockerComposeContainer.createServices(DockerComposeContainer.java:234)
 at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:176)
 at org.apache.paimon.tests.E2eTestBase.before(E2eTestBase.java:143)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
 at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
 at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
 at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
 at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
 at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
 at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
 at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
 at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
 at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
 at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:506)
 at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$21(ClassBasedTestDescriptor.java:491)
 at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$3(TestMethodTestDescriptor.java:171)
 at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:199)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:199)
 at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:168)
 at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
 at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
 at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
 at java.util.ArrayList.forEach(ArrayList.java:1259)
 at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
 at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
 at java.util.ArrayList.forEach(ArrayList.java:1259)
 at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
 at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
 at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
 at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
 at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
 at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
 at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
 at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
 at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
 at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
 at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
 at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
 at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
 at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
 at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
 at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
 at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
 at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
 at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
 at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
 at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
 at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

### Anything else?

Container will lookup for network whose **name** is ${NETWORK_ID}, however the the network was created with ID of ${NETWORK_ID} but **name** with a random UUID, which is different with ${NETWORK_ID}. Thus docker will failed to join a network which is not exist. 

![image](https://user-images.githubusercontent.com/26704332/231226278-fb53775f-982c-4d1a-86c3-3b62a91bf711.png)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by liming30** [comment]
I also ran into this problem. 
```
macos: 10.15.5
docker: 20.10.17
```
